small change in import statements
sugarlabs/jamath-activity pull request #22
Opened 2021-04-08 07:49 UTC by A-Rahul-535

writing "from gi.repository import Gtk" statement before "import gi" gives you error sometimes as we are importing Gtk without importing gi (it happened to me)
So, keeping the import statements in this order: 
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
This sequence seems to be more logical and works withour errors always
Please review @quozl @llaske @JuiP

2021-04-08 09:10 UTC, quozl commented
Thanks.

* [ ] don't see why it is necessary to change the position of `import os`,
* [ ] the commit message should contain what we need to review the commit (in history and in pull request), and currently it does not, see our [making commits](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits) list,

2021-04-08 09:47 UTC, A-Rahul-535 commented
> Thanks.
> 
> * [ ]  don't see why it is necessary to change the position of `import os`,
> * [ ]  the commit message should contain what we need to review the commit (in history and in pull request), and currently it does not, see our [making commits](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits) list,

2021-04-08 09:56 UTC, A-Rahul-535 commented
Before changing the position of import os, I got a warning as "pygiwarning: gtk was imported without specifying a version first. use gi.require_version('gtk', '3.0') before import to ensure that the right version gets loaded. from gi.repository import gtk" 
This warning was not displayed after changing the position.

Regarding the commit message, sorry for the inconvenience, i will take care of it from the next time.
Thanks..

2021-04-08 17:41 UTC, srevinsaju requested changes

2021-04-08 17:41 UTC, srevinsaju commented on juego.py
> +
This change looks redundant. The change which you say to be fixed is associated with only this https://github.com/sugarlabs/jamath-activity/pull/22/files#diff-decd061d3cbb8b9842a0677876d2db465b2f6dd0ad09106406b22304ea470d21R10, moving `os` shouldn't remove that warning as @quozl said.

2021-04-08 19:57 UTC, quozl commented
Well, although the mechanism by which a move to import os makes this error is difficult to postulate, it just means more evidence is needed.  Try it again, and demonstrate to us why the change is needed, and then we'll potentially be able to raise the issue with whomever should fix it in Python or PyGObject communities.  I've tried it, and I'm unable to reproduce the error you report.  Thanks!

2021-05-04 09:38 UTC, chimosky commented
@A-Rahul-535 do you intend to keep working on this?

2021-07-03 14:14 UTC, chimosky commented
Closing as this is stale and I got no response from the author.

2021-07-03 14:14 UTC, closed without merging